// What the site says about itself to things that aren't people: link
// previews (Open Graph), search engines (canonical URLs, schema.org JSON-LD,
// robots.txt, the sitemap) and password managers (the passkey endpoints).
// Pure — no database, no requests — so server.js looks the data up and this
// turns it into text, and the escaping rules can be tested on their own.
//
// Everything here ends up inside markup, XML or a <script> data block, and
// much of it is written by whoever made a tree. Each output format has its
// own escaper below, and nothing is interpolated without going through one.

const SITE_NAME = 'Skill Trees';

// The link-preview image, generated by tools/make-icons.js. 1200x630 is the
// 1.91:1 card that Open Graph consumers (and X's summary_large_image) crop
// least.
const SOCIAL_CARD = {
  path: '/social-card.png',
  type: 'image/png',
  width: 1200,
  height: 630,
  alt: 'Skill Trees: maps of how learning one skill unlocks the next.',
};

// A description longer than this is cut: search results show about 155
// characters and link previews fewer, so the rest is weight nobody reads.
const DESCRIPTION_MAX = 200;

// How many skill names go into JSON-LD's `teaches`. A tree can hold a
// thousand skills (FORMAT.md's limits); the page's <head> should not grow by
// 120 KB to say so. The first ones, in the order they were added, which is
// roughly the order they are learned in.
const MAX_TAUGHT = 50;

// sitemaps.org: at most 50,000 URLs in one sitemap file. One is the homepage.
const MAX_SITEMAP_URLS = 50000;

// ---------- escaping ----------

// For text content and quoted attribute values (HTML Standard §13.1.2.3,
// §13.1.2.6). Escaping all five means the same function is safe in either
// place, with either quote style.
function escapeHtml(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// XML 1.0's five predefined entities (§4.6), which is also exactly the list
// sitemaps.org says a <loc> must have escaped. Control characters other than
// tab, newline and carriage return are not allowed in XML 1.0 at all, even as
// references (§2.2), so they are dropped rather than escaped.
function escapeXml(value) {
  return String(value == null ? '' : value)
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\ufffe\uffff]/g, '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// JSON for the inside of a <script type="application/ld+json"> element.
// A script element's content ends at the first "</script" whatever it sits
// inside (HTML Standard §13.2.5.4, script data state), and "<!--" can switch
// the tokenizer into an escaped state where that rule shifts — so no "<" may
// appear at all. Escaping < > & as < > & keeps the JSON
// identical once parsed. U+2028 and U+2029 are legal in JSON strings but were
// line terminators in JavaScript before ES2019, which older consumers that
// eval the block choke on; they are escaped too.
function jsonForScript(value) {
  return JSON.stringify(value).replace(/[<>&\u2028\u2029]/g, (c) => {
    return '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0');
  });
}

// One line, at most `max` characters, cut at a word where there is one.
function oneLine(text, max = DESCRIPTION_MAX) {
  const flat = String(text == null ? '' : text).replace(/\s+/g, ' ').trim();
  if (flat.length <= max) return flat;
  const cut = flat.slice(0, max - 1);
  const space = cut.lastIndexOf(' ');
  return (space > max * 0.6 ? cut.slice(0, space) : cut).replace(/[\s.,;:!?-]+$/, '') + '…';
}

// SQLite's datetime('now') ("2026-09-24 08:09:01", UTC) as the W3C Datetime
// profile of ISO 8601 that sitemaps.org, schema.org and Open Graph all ask
// for: "2026-09-24T08:09:01Z". null when it doesn't look like one.
function isoDatetime(sqliteDate) {
  const m = /^(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2}:\d{2})/.exec(String(sqliteDate || ''));
  return m ? `${m[1]}T${m[2]}Z` : null;
}

// ---------- page metadata ----------

// Pages mark where generated metadata goes with HTML comments, so nothing
// here has to find its way through arbitrary markup with a regex:
//
//   <!--@page-urls-->                     replaced by canonical / og:url /
//                                         og:image / twitter:card
//   <!--@tree-meta--> ... <!--/@tree-meta-->  in tree.html: the generic
//                                         title and description, replaced
//                                         as a block when a tree is shown
//
// The markers are located in the file as read from disk, before anything is
// inserted, and spliced with slice() rather than String.replace(): replace()
// expands "$&" and "$'" in its replacement, which in a tree's title would
// copy pieces of the page into the output.
const PAGE_URLS = '<!--@page-urls-->';
const TREE_BEGIN = '<!--@tree-meta-->';
const TREE_END = '<!--/@tree-meta-->';

// The address a page is known by, or null for one that has no address of
// its own worth sharing: a draft or a missing tree (tree.html without a tree
// to show), and the offline fallback.
function canonicalPath(pagePath, tree) {
  if (pagePath === '/index.html') return '/';
  if (pagePath === '/tree.html') return tree ? `/tree.html?id=${tree.id}` : null;
  if (pagePath === '/offline.html') return null;
  return pagePath;
}

// Open Graph requires og:url and og:image to be absolute URLs, and so does
// rel=canonical in practice, so they exist only when PUBLIC_ORIGIN says what
// the site's absolute URLs are. Building them from the Host header instead
// would let whoever sends the request choose the domain a crawler files the
// page under. Without an image the card type falls back to "summary".
function pageUrlsHead({ origin, path }) {
  if (!origin) return '<meta name="twitter:card" content="summary" />';
  const lines = [];
  if (path) {
    const url = escapeHtml(origin + path);
    lines.push(`<link rel="canonical" href="${url}" />`);
    lines.push(`<meta property="og:url" content="${url}" />`);
  }
  lines.push(`<meta property="og:image" content="${escapeHtml(origin + SOCIAL_CARD.path)}" />`);
  lines.push(`<meta property="og:image:type" content="${SOCIAL_CARD.type}" />`);
  lines.push(`<meta property="og:image:width" content="${SOCIAL_CARD.width}" />`);
  lines.push(`<meta property="og:image:height" content="${SOCIAL_CARD.height}" />`);
  lines.push(`<meta property="og:image:alt" content="${escapeHtml(SOCIAL_CARD.alt)}" />`);
  lines.push('<meta name="twitter:card" content="summary_large_image" />');
  return lines.join('\n');
}

// The schema.org description of a tree (a LearningResource: something you
// learn from, which teaches the skills in it). Only what the page itself
// shows, so the structured data never says more than the visible page does.
function treeJsonLd({ tree, skillNames, origin }) {
  const created = isoDatetime(tree.created_at);
  const data = {
    '@context': 'https://schema.org',
    '@type': 'LearningResource',
    name: tree.title,
  };
  if (tree.description && tree.description.trim()) data.description = tree.description;
  if (tree.author && tree.author.trim()) data.author = { '@type': 'Person', name: tree.author };
  if (created) data.dateCreated = created;
  if (origin) data.url = `${origin}/tree.html?id=${tree.id}`;
  if (skillNames.length) data.teaches = skillNames.slice(0, MAX_TAUGHT);
  data.isAccessibleForFree = true;
  return data;
}

// The <head> lines for one tree: what the page will call itself once its
// script has run, available before any script does — to a crawler, a link
// preview, or a slow connection.
function treeHead({ tree, skillCount, skillNames, origin }) {
  const title = tree.title;
  const skills = `${skillCount} skill${skillCount === 1 ? '' : 's'}`;
  const description =
    oneLine(tree.description) ||
    oneLine(`${title}: a skill tree of ${skills}${tree.author ? `, by ${tree.author}` : ''}.`);
  const created = isoDatetime(tree.created_at);
  const lines = [
    `<title>${escapeHtml(title)} — ${SITE_NAME}</title>`,
    `<meta name="description" content="${escapeHtml(description)}" />`,
    '<meta property="og:type" content="article" />',
    `<meta property="og:title" content="${escapeHtml(title)}" />`,
    `<meta property="og:description" content="${escapeHtml(description)}" />`,
  ];
  if (created) lines.push(`<meta property="article:published_time" content="${created}" />`);
  lines.push(
    `<script type="application/ld+json">${jsonForScript(treeJsonLd({ tree, skillNames, origin }))}</script>`
  );
  return lines.join('\n');
}

// A page as it goes out: the file from disk with its markers filled in.
//   pagePath  the file's path under frontend/ ("/tree.html")
//   origin    PUBLIC_ORIGIN, or null
//   tree      { tree, skillCount, skillNames } for a tree page, else null
// A page with no markers comes back exactly as it went in; so does a tree
// block whose closing marker is missing, rather than losing the rest of the
// <head> to it.
function renderPage(html, { pagePath, origin = null, tree = null }) {
  // Every span is located in the template before anything is inserted, and
  // the output is assembled from the template's own pieces, so text written
  // into one span is never searched for the next marker. (It couldn't match
  // anyway — nothing inserted contains a "<" that isn't markup we wrote —
  // but this way that holds by construction, not by escaping.)
  const edits = [];
  const urlsAt = html.indexOf(PAGE_URLS);
  if (urlsAt !== -1) {
    const path = canonicalPath(pagePath, tree && tree.tree);
    edits.push([urlsAt, urlsAt + PAGE_URLS.length, pageUrlsHead({ origin, path })]);
  }
  if (tree) {
    const begin = html.indexOf(TREE_BEGIN);
    const end = begin === -1 ? -1 : html.indexOf(TREE_END, begin + TREE_BEGIN.length);
    if (end !== -1) edits.push([begin, end + TREE_END.length, treeHead({ ...tree, origin })]);
  }
  edits.sort((a, b) => a[0] - b[0]);
  let out = '';
  let pos = 0;
  for (const [start, stop, text] of edits) {
    if (start < pos) continue; // a marker inside another span: the outer one wins
    out += html.slice(pos, start) + text;
    pos = stop;
  }
  return out + html.slice(pos);
}

// ---------- robots.txt, sitemap.xml, passkey endpoints ----------

// RFC 9309. One group for every crawler: the pages are all public, and the
// API is data behind them — its responses already say X-Robots-Tag: noindex,
// and Disallow keeps crawlers from spending their budget on it at all. The
// Sitemap line (§2.2.4 leaves room for "other records"; sitemaps.org defines
// it) must be an absolute URL, so it is only there when PUBLIC_ORIGIN is.
function robotsTxt(origin) {
  const lines = ['# Skill Trees (RFC 9309)', 'User-agent: *', 'Allow: /', 'Disallow: /api/'];
  if (origin) lines.push('', `Sitemap: ${origin}/sitemap.xml`);
  return lines.join('\n') + '\n';
}

// sitemaps.org protocol 0.9: the homepage and every tree page, absolute and
// entity-escaped. `trees` is [{ id, created_at }], at most
// MAX_SITEMAP_URLS - 1 of them. lastmod is when the tree was made: there is
// no updated_at column yet (TODO.md), and a lastmod that claims to know more
// than it does is worse than none — which is also why the homepage, whose
// list changes with every tree, has none.
function sitemapXml(origin, trees) {
  const out = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    `<url><loc>${escapeXml(origin + '/')}</loc></url>`,
  ];
  for (const t of trees.slice(0, MAX_SITEMAP_URLS - 1)) {
    const lastmod = isoDatetime(t.created_at);
    out.push(
      `<url><loc>${escapeXml(`${origin}/tree.html?id=${t.id}`)}</loc>` +
        (lastmod ? `<lastmod>${lastmod}</lastmod>` : '') +
        '</url>'
    );
  }
  out.push('</urlset>');
  return out.join('\n') + '\n';
}

// W3C "A Well-Known URL for Relying Party Passkey Endpoints": where a
// password manager can send someone to add a passkey (enroll) or look after
// the ones they have (manage). The spec's members are URLs a client opens as
// they are — it defines no base to resolve a relative one against, and its
// examples are absolute — so this exists only when PUBLIC_ORIGIN does.
function passkeyEndpoints(origin) {
  const page = `${origin}/account.html#account-passkeys`;
  return { enroll: page, manage: page };
}

module.exports = {
  SITE_NAME,
  SOCIAL_CARD,
  MAX_TAUGHT,
  MAX_SITEMAP_URLS,
  PAGE_URLS,
  TREE_BEGIN,
  TREE_END,
  escapeHtml,
  escapeXml,
  jsonForScript,
  oneLine,
  isoDatetime,
  canonicalPath,
  treeJsonLd,
  treeHead,
  renderPage,
  robotsTxt,
  sitemapXml,
  passkeyEndpoints,
};
